require('dotenv').config();
const express=require('express');
const cors=require('cors');
const session=require('express-session');
const path=require('path');
const app=express();
const PORT=process.env.PORT||3000;
app.use(cors());
app.use(express.json({limit:'10mb'}));
app.use(express.urlencoded({extended:true,limit:'10mb'}));
app.use(session({secret:process.env.SESSION_SECRET||'sidus-rahasia',resave:false,saveUninitialized:false,cookie:{maxAge:1000*60*60*8}}));
app.use(express.static(path.join(__dirname,'public')));
app.use('/uploads',express.static(path.join(__dirname,'uploads')));
app.use('/api/auth',require('./routes/auth'));
app.use('/api/profil',require('./routes/profil'));
app.use('/api/rt',require('./routes/rt'));
app.use('/api/warga',require('./routes/warga'));
app.use('/api/iuran',require('./routes/iuran'));
app.use('/api/pengaduan',require('./routes/pengaduan'));
app.use('/api/surat',require('./routes/surat'));
app.get('/health',(req,res)=>res.json({ok:true,app:'SIDUS Dusun 02'}));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public/index.html')));
app.listen(PORT,()=>console.log('SIDUS berjalan di port '+PORT));
